DROP DATABASE ig_clone;
CREATE DATABASE ig_clone;
USE ig_clone;
CREATE TABLE users(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT
,username VARCHAR(100) UNIQUE NOT NULL
,created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE photos(
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL
,image_url VARCHAR(255) NOT NULL
,user_id INT NOT NULL
,created_at TIMESTAMP  DEFAULT NOW()
,FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE comments(
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL
,comment_text VARCHAR(255) NOT NULL
,user_id INT NOT NULL
,photo_id INT NOT NULL
,created_at TIMESTAMP DEFAULT NOW()
,FOREIGN KEY (user_id) REFERENCES users(id)
,FOREIGN KEY (photo_id) REFERENCES photos(id)
);
 