DROP DATABASE ig_clone;
CREATE DATABASE ig_clone;
USE ig_clone;
CREATE TABLE users(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT
,username VARCHAR(100) UNIQUE NOT NULL
,created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE photos(
id INT AUTO_INCREMENT PRIMARY KEY
,image_url VARCHAR(255) NOT NULL
,user_id INT NOT NULL
,created_at TIMESTAMP  DEFAULT NOW()
,FOREIGN KEY (user_id) REFERENCES users(id)
);